### PR TITLE
GUI Update

### PR DESCRIPTION
**Pull request by sc1341**
Change List:

Started GUI 

Changed arguments in function calls to keyword arguments to make it easier to read

Cleaned Comments and Doc Strings

Fixed Arg Parse/Cml interface -- Check out the README.md for more info or run `python3 Buggify.py -h`

Removed Top Comments of the script because we covered it in the README.md

Renamed the diff_output function to answer_key_generate

Renamed a few variables for clarification

Created an update .exe file

Let me know what your initial thoughts are and any critiques that you have!

Thanks!

### CODE REVIEW

**Comment by roovyshapiro** [comment]
This is incredible work! Thank you again for your time and effort with this pull request. I'm going to review it as soon as I find some time and will let you know any thoughts I have. Thanks!

**Comment by roovyshapiro** [comment]
@sc1341 This looks awesome so far!

I've run into a few small issues when trying to run this so far.
Note: I'm using powershell/Windows to test the GUI/command line arguments.

- 1: Argument of type 'NoneType' is not iterable
- 2: Path should be... not list.
https://i.imgur.com/XwtyQYH.png

- 3: The GUI throws an error why I leave the textbox blank:
https://i.imgur.com/cH0AofW.png

- 4: Command line arguments are not optional. 
https://i.imgur.com/oYBnUx8.png

- 5: Tkinter Window stuff
https://i.imgur.com/IEdobzs.gifv
I'm not that familiar with Tkinter yet, there are a number of basic layout/features that are missing from here. I know it's the first revision so it doesn't have to be perfect. If we could fix all the bugs which prevent it from running as intended, we could merge this and then make it more user friendly after.

- 6: "--bugs scl, abs3, chars, cases"
These arguments aren't very intuitive. If you read the documentation, then it becomes clear. But should it be easier to understand what they are when running from command line? I'm not sure about this. What if the help showed which bug abbreviations went to which bugs with brief one line descriptions? Need to think about this.

Anyways, that was my first impression. It is a huge step in the right direction and again, thank you for all your hard work. Definitely getting close to what I had in mind with the GUI. We could merge this into a testing-gui branch and work on it from there.
What are your thoughts?

**Comment by sc1341** [comment]
Thanks for looking at it! Below I will add a few comments and questions to the issues...

One really dumb thing I did is I left in the old argument parser code from before... I removed that now and this should resolve a few of the errors... sorry!

1. I will take a look at the NoneType, this is probably due to the fact that the variable is never assigned a value or it is not assigned properly using the default keyword argument in the add_argument function.

2. Probably the dumb argparse code that I left in (I'm kicking myself for this one lol)

3. Fixed it with the new commit, it now displays a message box when the field is empty with an error prompting the user to put in a number.

4. I'm not sure about this one yet, I will research a little into the argparse module. 

5. Tkinter has a few different options for the placement of objects. I used the .grid method on these but perhaps the "place" method could be better due to the fact that it moves around the screen when the user changes the size of the window.

6. I agree, we could definitely add better definitions in the "help" menu from the command line. 

I think we can merge to a GUI Branch once I clean up the little bugs I have in the code...

Thanks!
sc1341

**Comment by roovyshapiro** [comment]
Thank you for your work with this.

I merged this into the testing-GUI branch and removed some of the files that were added by mistake. I need to do some more testing on it before we merge it to master, but it was definitely good enough to have its own branch.

Thank you!

Relevant issues:
#9 
#14

**Pull request merged**
